version: 2

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/simontheleg/deepwork
    environment:
      TEST_RES_DIR: /tmp/test-results
      ARTIFACTS_DIR: /tmp/artifacts
    steps:
      - checkout
      - run:
          name: Create required dirs
          command: | 
            mkdir ${TEST_RES_DIR}
            mkdir ${ARTIFACTS_DIR}
      # This dependency is required to convert 'go test' results to junit ones for Circle CI to automatically recognize them
      - run: 
          name: Fetch go-junit-report
          command: go get github.com/jstemmer/go-junit-report
      - run: 
          name: Resolve dependencies with go-get
          command: go get -v -t -d ./...
      - run: 
          name: Run go test
          command: |
            go test -v -cover ./... | tee ${TEST_RES_DIR}/go-test.out
            go-junit-report <${TEST_RES_DIR}/go-test.out > ${TEST_RES_DIR}/go-test-report.xml
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Build app
          command: go build -o ${ARTIFACTS_DIR}/deepwork
      - persist_to_workspace:
          root: ${ARTIFACTS_DIR}
          paths:
            - ./*
  
  publish-github-release:
    docker:
      - image: simontheleg/github-go-releaser
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Testy
          command: ls -la

