version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/simontheleg/deepwork
    steps:
      - checkout
      - run:
          name: Create required dirs
          command: mkdir /tmp/test-results
      - run: 
          name: Resolve dependencies with go-get
          command: go get -v -t -d ./...
      - run: 
          name: Run go test
          command: go test -v -cover ./... | tee /tmp/test-results/unit-test
      - store_test_results:
          path: /tmp/test-results